services:
  web:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NOTION_API_KEY: ${NOTION_API_KEY}
      NOTION_POST_DATABASE_ID: ${NOTION_POST_DATABASE_ID}
      NOTION_PROJECT_DATABASE_ID: ${NOTION_PROJECT_DATABASE_ID}
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
