services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      NOTION_API_KEY: ${NOTION_API_KEY}
      NOTION_POST_DATABASE_ID: ${NOTION_POST_DATABASE_ID}
      NOTION_PROJECT_DATABASE_ID: ${NOTION_PROJECT_DATABASE_ID}
      # Optional S3 for local testing
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      AWS_REGION: ${AWS_REGION}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_PUBLIC_BASE_URL: ${S3_PUBLIC_BASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static

volumes:
  pgdata:
